### ISSUE TITLE
Update Deployment apiVersion and spec.selectors for k8s 1.16

### ISSUE THREAD

**Issue by hanskohls** [digitalocean/doks-example#4]
DO's k8s has now been updated to version 1.16. 

The Deployment version `extensions/v1beta1` in the manifest.yaml is outdated and should be replaced with `apps/v1`

Details on this deprecation can be found [here](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)

The new setup also needs a change to the selector: 

```
spec:
  selectors:
    matchLabels: 
      app: doks-example
```
